---
on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: 6.0.400

jobs:
  deploy-infra:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: 'Run az commands'
        run: |
          az group create --location ${{ secrets.AZURE_LOCATION }} --resource-group ${{ secrets.RESOURCE_GROUP_NAME }}
      - name: 'Deploy Bicep'
        id: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.RESOURCE_GROUP_NAME }}
          template: ./main.bicep
          parameters: sqlAdministratorLogin=${{ secrets.SQL_ADMIN_LOGIN }} sqlAdministratorLoginPassword=${{ secrets.SQL_ADMIN_PASSWORD }}
          failOnStderr: true
      - name: 'Check sqlserver DNS result from public'
        run: | 
          az rest --method post --resource https://management.core.windows.net --url https://websitebmchpnzjithzo.scm.azurewebsites.net/api/command --body '{"command": "nslookup ${{ steps.deploy.outputs.sqlserverDns }}","dir": "C:\\home\\site\\wwwroot"}' --headers Content-Type=application/json
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: dotnet build and publish
        working-directory: ./application
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o ./publish
      - name: 'Deploy public application'
        uses: azure/webapps-deploy@v2
        with:
          app-name: websitebmchpnzjithzo
          package: ./application/publish
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
      - name: 'Deploy private application'
        uses: azure/webapps-deploy@v2
        with:
          app-name: privatewebsitebmchpnzjithzo
          package: ./application/publish
          publish-profile: ${{ secrets.PRIVATE_PUBLISH_PROFILE }}
        